# Generated by Django 4.0.4 on 2022-05-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
